module.exports = {
    WORD_INPUT_VALUE:  'WORD_INPUT_VALUE',
    WORD_CLEAR_INPUT:  'WORD_CLEAR_INPUT',
    WORD_HELP:         'WORD_HELP',
    WORD_GENERATE:     'WORD_GENERATE',
    WORD_INPUT_CUSTOM: 'WORD_INPUT_CUSTOM'
};
